class Constants {
    static final String BURSA_ANNOUNCEMENTS_URL = 'http://announcements.bursamalaysia.com/'
    static final String KLSE_SCREENER_URL = 'http://www.klsescreener.com/v2/screener/quote_results/'
    static final String STARBIZ_INDICES_JSON_URL = 'http://biz.thestar.com.my.s3.amazonaws.com/json/indices.js'
    static final String URL_PREFIX = 'http://announcements.bursamalaysia.com/EDMS%5CEdmsWeb.nsf/dfDisplayForm?Openform&Count=-1&form=dfDisplayForm&viewname=LsvAnnsAll&category='
    static final int ANNOUNCEMENTS_LIMIT = 10000

    // Ref URL: https://cloud.google.com/appengine/docs/java/urlfetch/#Java_Quotas_and_limits
    static final int CONNECT_TIMEOUT = 15000
    static final int READ_TIMEOUT = 5000

    static final String DEFAULT_DATE_TIME_FORMAT = 'dd MMM yyyy HH:mm:ss'
    static final TimeZone DEFAULT_TIME_ZONE = TimeZone.getTimeZone('Asia/Kuala_Lumpur')

    static final String FBM_INDICES = 'FBM_INDICES'
    static final String FBMKLCI_NAME = 'FBMKLCI'
    static final String FBMKLCI_COMPONENTS = 'AMBANK,ASTRO,AXIATA,BAT,CIMB,DIGI,FGV,GENTING,GENM,HLBANK,HLFG,IHH,IOICORP,KLCC,KLK,MAYBANK,MAXIS,MISC,PCHEM,PETDAG,PETGAS,PPB,PBBANK,RHBCAP,SKPETRO,SIME,TM,TENAGA,UMW,YTL'

    static final String FBM70_NAME = 'FBM70'
    static final String FBM70_COMPONENTS = 'AAX,AEONCR,AFG,AIRASIA,AIRPORT,ARMADA,BIMB,BJCORP,BJTOTO,BURSA,CARLSBG,CMMT,CMSB,COASTAL,DAYANG,DIALOG,DRBHCOM,DSONIC,E&O,GAMUDA,GASMSIA,GENP,HAPSENG,HARTA,HLCAP,IGB,IGBREIT,IJM,IOIPG,JTIASA,KOSSAN,KPJ,KSENG,KULIM,LAFMSIA,MAGNUM,MAHSING,MAYBULK,MBSB,MEDIA,MEDIAC,MHB,MMCCORP,MRCB,MUDAJYA,OSK,PARKSON,PAVREIT,PERISAI,POS,QL,SPSETIA,SUNWAY,SUPERMX,TAANN,TAGB,TDM,TIMECOM,TOPGLOV,TROP,TSH,UEMS,UMWOG,UOADEV,WCT,WPRTS,YINSON,YTLPOWR'

    static final String FBMSCAP_NAME = 'FBMSCAP'
    static final String FBMSCAP_COMPONENTS = '3A,A&M,AJI,ALAM,AMFIRST,AMPROP,ANNJOO,ASIABRN,AZRB,BENALEC,BJAUTO,BJFOOD,BONIA,BRAHIMS,BREM,CANONE,CARING,CBIP,CCB,CCM,CENSOF,CENTURY,CEPAT,CHINWEL,CLIQ,CRESNDO,CSL,CYPARK,DAIMAN,DAYA,DELEUM,DESTINI,DKSH,DNEX,DUTALND,ECM,ECOWLD,EDGENTA,ENCORP,ENGTEX,FAJAR,FAVCO,FITTERS,GADANG,GBGAQRS,GLOMAC,GOB,GPACKET,GTRONIC,GUH,GUOCO,HAIO,HIBISCS,HLIND,HOVID,HUAYANG,HUBLINE,HUNZPTY,IBHD,INSAS,IVORY,IWCITY,JAKS,JCY,KAREX,KBUNAI,KENANGA,KEURO,KFIMA,KIANJOO,KIMLUN,KINSTEL,KKB,KNM,KPS,KRETAM,KSL,KUB,L&G,LANDMRK,LATITUD,LBS,LIONDIV,LIONIND,MAA,MALTON,MASTEEL,MATRIX,MEGB,MFLOUR,MHC,MITRA,MKH,MKLAND,MNRB,MPHBCAP,MQREIT,MSC,MUHIBAH,MUIIND,MULPHA,MYEG,NAIM,NOTION,NTPM,OLDTOWN,OLYMPIA,OMESTI,OSKPROP,P&O,PADINI,PANTECH,PBA,PELIKAN,PENERGY,PERDANA,PESTECH,PHARMA,PJDEV,POHKONG,PRESBHD,PRKCORP,PRTASCO,PTARAS,PUNCAK,PWROOT,RCECAP,RSAWIT,SALCON,SBCCORP,SCABLE,SCICOM,SCIENTX,SCOMI,SCOMIES,SEG,SENDAI,SILKHLD,SKPRES,SONA,STAR,SUMATEC,SYMLIFE,TA,TAKAFUL,TALAMT,TAMBUN,TGOFFS,THHEAVY,TITIJYA,TMCLIFE,TNLOGIS,TRC,TUNEINS,UCHITEC,UNISEM,UZMA,WELLCAL,WTK,XINQUAN,YEELEE,YNHPROP,YTLLAND,YTLREIT,ZELAN,ZHULIAN'

    static final String FBMT100_NAME = 'FBMT100'
    static final String FBMEMAS_NAME = 'FBMEMAS'
}