import com.google.appengine.api.datastore.*


Date now = new Date()
StockIndex stockIndex

if (params.init) {
	def indexMap = ['15 Jun 2015':[
		'FBMKLCI': Constants.FBMKLCI_COMPONENTS,
		'FBM70': Constants.FBM70_COMPONENTS,
		'FBMSCAP': Constants.FBMSCAP_COMPONENTS
	], '22 Jun 2015': [
		'FBMKLCI': 'AMBANK,ASTRO,AXIATA,BAT,CIMB,DIGI,GENTING,GENM,HLBANK,HLFG,IHH,IOICORP,KLCC,KLK,MAYBANK,MAXIS,MISC,PCHEM,PETDAG,PETGAS,PPB,PBBANK,RHBCAP,SKPETRO,SIME,TM,TENAGA,UMW,WPRTS,YTL',
		'FBM70': 'AAX,AEONCR,AFG,AIRASIA,AIRPORT,ARMADA,BIMB,BJCORP,BJTOTO,BURSA,CARLSBG,CMMT,CMSB,COASTAL,DAYANG,DIALOG,DRBHCOM,DSONIC,E&O,ECOWLD,FGV,GAMUDA,GASMSIA,GENP,HAPSENG,HARTA,HLCAP,HUMEIND,IGBREIT,IJM,IOIPG,KAREX,KOSSAN,KPJ,KSENG,KULIM,LAFMSIA,MAGNUM,MAHSING,MBSB,MEDIA,MEDIAC,MHB,MMCCORP,MRCB,MUDAJYA,OSK,PARKSON,PAVREIT,PERISAI,PHARMA,PMETAL,POS,QL,SPSETIA,SUNREIT,SUNWAY,SUPERMX,TAANN,TAGB,TDM,TIMECOM,TOPGLOV,TROP,UEMS,UMWOG,UOADEV,WCT,YINSON,YTLPOWR',
		'FBMSCAP': '3A,A&M,AJI,ALAM,AMFIRST,AMPROP,ARREIT,ASIABRN,AZRB,BENALEC,BJAUTO,BJFOOD,BOILERM,BONIA,BRAHIMS,BREM,CANONE,CARING,CBIP,CENSOF,CENTURY,CHINWEL,CLIQ,CRESNDO,CSL,CYPARK,DAYA,DELEUM,DESTINI,DKSH,DNEX,DUTALND,EATECH,ECS,EDGENTA,ELSOFT,ENCORP,ENGTEX,FAJAR,FAVCO,FITTERS,FRONTKN,GADANG,GBGAQRS,GKENT,GLOTEC,GOB,GPACKET,GTRONIC,GUH,GUOCO,HEVEA,HIBISCS,HLIND,HOVID,HUAYANG,HUNZPTY,IBHD,INSAS,IRCB,IVORY,IWCITY,JAKS,JCY,JOBST,KBUNAI,KENANGA,KFIMA,KIANJOO,KIMLUN,KINSTEL,KNM,KPS,KSL,KUB,L&G,LANDMRK,LATITUD,LBS,LIONDIV,LIONIND,MAA,MALTON,MASTEEL,MATRIX,MAYBULK,MCT,MEGB,MHC,MITRA,MKH,MKLAND,MNRB,MPHBCAP,MQREIT,MSC,MUHIBAH,MUIIND,MULPHA,MYEG,NAIM,NTPM,OCK,OLDTOWN,OLYMPIA,OMESTI,OSKPROP,OWG,P&O,PADINI,PANTECH,PBA,PELIKAN,PENERGY,PERDANA,PESTECH,PJDEV,POHKONG,PRESBHD,PRKCORP,PRTASCO,PTARAS,PUNCAK,PWROOT,RCECAP,RSAWIT,SALCON,SASBADI,SBCCORP,SCABLE,SCICOM,SCIENTX,SCOMI,SCOMIES,SEG,SENDAI,SILKHLD,SKPRES,SONA,SUMATEC,SUNSURIA,SYMLIFE,TA,TAKAFUL,TALAMT,TAMBUN,TASCO,TEOSENG,TGOFFS,THHEAVY,TITIJYA,TMCLIFE,TNLOGIS,TUNEINS,UCHITEC,ULICORP,UNISEM,UZMA,VS,WELLCAL,WTK,XINQUAN,YEELEE,YNHPROP,YTLREIT,ZELAN,ZHULIAN'
	]]
	indexMap.each { effectiveDate, stockIndexes ->
		stockIndexes.each { name, components -> 
			stockIndex = new StockIndex(effectiveDate:Date.parse(Constants.DEFAULT_DATE_FORMAT, effectiveDate), created: now)
			stockIndex.name = name
			stockIndex.components = components
			stockIndex.save()
			stockIndex = null
		}
	}
	println "stockIndexes initialized."
} else {
	stockIndex = new StockIndex(name: params.name, components:params.c, effectiveDate:Date.parse(Constants.DEFAULT_DATE_FORMAT, params.date), created: now)
	stockIndex.save()
	println "${stockIndex} created."	
}
